"""tpot2cti — configuration loader.

Loads runtime configuration from two sources, in priority order:

  1. Environment variables (as documented in `.env.example`)
  2. YAML config file at /etc/tpot2cti/config.yaml (optional, for non-
     secret behavioral settings like ignore_types, batch_size, etc.)

The env file is the canonical source of truth for secrets (OPENCTI_TOKEN,
SSH credentials, API keys).  YAML is for verbose behavioral knobs that
don't fit cleanly in env vars.

This module deliberately does NOT load `.env` from disk — that's
docker-compose's job.  We just read what's already in `os.environ`.
For unit-test convenience, callers can pass an explicit `env_dict` to
`load_config()` to override.

Per V1_SPEC.md §10 (the configuration reference) and
docs/LESSONS_LEARNED_FROM_V0.md §8.2 (the `CONNECTOR_ID=""` /
`BAD_USER_INPUT` footgun — we validate required fields up front).
"""

from __future__ import annotations

import logging
import os
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Dataclasses for the resolved config — typed access for downstream callers
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class TPotConfig:
    """T-Pot connection settings (SSH tunnel target)."""
    host: str
    ssh_user: str = "tpot"
    ssh_port: int = 64295
    #: Self-filter: every ParsedEvent whose `src_ip` is in this set gets
    #: dropped before correlation. Catches the case where Suricata
    #: logs an event from the honeypot's own outbound side (e.g. our
    #: H0neytr4p replying with `Host: www.google.com` deceptive HTML —
    #: src_ip is OUR public IP, not an attacker). Populate via
    #: `TPOT_HONEYPOT_IPS` env var (comma-separated).
    honeypot_ips: frozenset[str] = frozenset()


@dataclass(frozen=True)
class ESConfig:
    """T-Pot Elasticsearch endpoint (via tunnel by default)."""
    host: str = "tunnel"
    port: int = 64298
    scheme: str = "http"
    username: Optional[str] = None
    password: Optional[str] = None
    verify_certs: bool = False
    index_pattern: str = "logstash-*"
    request_timeout: int = 30


@dataclass(frozen=True)
class OpenCTIConfig:
    """OpenCTI platform connection settings."""
    url: str
    admin_token: str


@dataclass(frozen=True)
class OperatorConfig:
    """Operator identity stamped on every emitted STIX object."""
    org_name: str = "T-Pot Operator"
    default_tlp: str = "AMBER+STRICT"
    default_confidence: int = 75


@dataclass(frozen=True)
class CycleConfig:
    """Importer cycle behavior."""
    interval_iso: str = "PT15M"             # ISO 8601 duration
    initial_lookback_hours: int = 0          # 0 = "start fresh from now"
    ignore_types: list[str] = field(default_factory=list)
    batch_size: int = 1000
    cycle_anchor_hour_utc: Optional[int] = None  # None = no anchor sleep
    transient_retry_seconds: int = 60       # per LESSONS_LEARNED §5


@dataclass(frozen=True)
class ConnectorIDs:
    """OpenCTI connector UUIDs — generated by setup.sh and read here."""
    core: str
    credentials: Optional[str] = None
    vault: Optional[str] = None


@dataclass(frozen=True)
class LoggingConfig:
    """File logging behavior — stdout is always on."""
    level: str = "INFO"
    log_dir: str = "/var/log/tpot2cti"
    retention_days: int = 30


@dataclass(frozen=True)
class Config:
    """Top-level resolved config — what callers actually use."""
    tpot: TPotConfig
    es: ESConfig
    opencti: OpenCTIConfig
    operator: OperatorConfig
    cycle: CycleConfig
    connector_ids: ConnectorIDs
    logging: LoggingConfig


# ---------------------------------------------------------------------------
# Loader
# ---------------------------------------------------------------------------

class ConfigError(ValueError):
    """Raised when a required config value is missing or invalid."""


def _env_str(env: dict, key: str, default: Optional[str] = None,
              required: bool = False) -> Optional[str]:
    val = env.get(key, default)
    if val is None and required:
        raise ConfigError(
            f"Missing required environment variable: {key}. "
            f"Did setup.sh run successfully?  See V1_SPEC.md §10."
        )
    if isinstance(val, str):
        val = val.strip()
        if not val and required:
            raise ConfigError(
                f"Environment variable {key} is empty. "
                f"This usually means docker compose couldn't find .env — "
                f"check that --env-file ./.env was passed (see "
                f"docs/LESSONS_LEARNED_FROM_V0.md §8.2 + §9.2)."
            )
    return val


def _env_int(env: dict, key: str, default: int) -> int:
    raw = env.get(key)
    if raw is None or raw == "":
        return default
    try:
        return int(raw)
    except (TypeError, ValueError) as e:
        raise ConfigError(f"{key} must be an integer; got {raw!r}") from e


def _env_bool(env: dict, key: str, default: bool) -> bool:
    """Truthy-env helper, per V2_OPENSOURCE_HANDOFF §3 (`tsec_env.truthy_env`).

    Accept 1/true/yes/on (any case) as True; 0/false/no/off as False.
    Empty or unset = default.
    """
    raw = env.get(key)
    if raw is None:
        return default
    s = str(raw).strip().lower()
    if not s:
        return default
    if s in ("1", "true", "yes", "on"):
        return True
    if s in ("0", "false", "no", "off"):
        return False
    raise ConfigError(f"{key} must be truthy/falsey; got {raw!r}")


def _env_list(env: dict, key: str, default: Optional[list[str]] = None,
               sep: str = ",") -> list[str]:
    raw = env.get(key)
    if not raw:
        return list(default or [])
    return [s.strip() for s in raw.split(sep) if s.strip()]


def load_config(env_dict: Optional[dict] = None) -> Config:
    """Load and validate config from environment.

    Pass `env_dict` to override `os.environ` (useful for tests).  By
    default reads `os.environ`.

    Raises `ConfigError` on missing/invalid required values, with a
    clear message pointing at V1_SPEC.md and the lessons-learned doc.
    """
    env = dict(env_dict if env_dict is not None else os.environ)

    # --- T-Pot connection ---
    # honeypot_ips: comma-separated. Strip whitespace, skip empties.
    raw_honeypot_ips = _env_str(env, "TPOT_HONEYPOT_IPS", default="") or ""
    honeypot_ips = frozenset(
        ip.strip() for ip in raw_honeypot_ips.split(",") if ip.strip()
    )
    tpot = TPotConfig(
        host=_env_str(env, "TPOT_HOST", required=True),
        ssh_user=_env_str(env, "TPOT_SSH_USER", default="tpot") or "tpot",
        ssh_port=_env_int(env, "TPOT_SSH_PORT", default=64295),
        honeypot_ips=honeypot_ips,
    )

    # --- T-Pot Elasticsearch ---
    es = ESConfig(
        host=_env_str(env, "ES_HOST", default="tunnel") or "tunnel",
        port=_env_int(env, "ES_PORT", default=64298),
        scheme=_env_str(env, "ES_SCHEME", default="http") or "http",
        username=_env_str(env, "ES_USERNAME"),
        password=_env_str(env, "ES_PASSWORD"),
        verify_certs=_env_bool(env, "ES_VERIFY_CERTS", default=False),
        index_pattern=_env_str(env, "ES_INDEX_PATTERN", default="logstash-*") or "logstash-*",
        request_timeout=_env_int(env, "ES_REQUEST_TIMEOUT", default=30),
    )

    # --- OpenCTI ---
    opencti = OpenCTIConfig(
        url=_env_str(env, "OPENCTI_URL", default="http://opencti:8080") or "http://opencti:8080",
        admin_token=_env_str(env, "OPENCTI_ADMIN_TOKEN", required=True),
    )

    # --- Operator identity ---
    operator = OperatorConfig(
        org_name=_env_str(env, "OPERATOR_ORG_NAME", default="T-Pot Operator") or "T-Pot Operator",
        default_tlp=_env_str(env, "TPOT2CTI_DEFAULT_TLP", default="AMBER+STRICT") or "AMBER+STRICT",
        default_confidence=_env_int(env, "TPOT2CTI_DEFAULT_CONFIDENCE", default=75),
    )

    # --- Cycle behavior ---
    cycle = CycleConfig(
        interval_iso=_env_str(env, "TPOT2CTI_INTERVAL", default="PT15M") or "PT15M",
        initial_lookback_hours=_env_int(env, "TPOT2CTI_INITIAL_LOOKBACK_HOURS", default=0),
        ignore_types=_env_list(env, "TPOT2CTI_IGNORE_TYPES", default=[]),
        batch_size=_env_int(env, "TPOT2CTI_BATCH_SIZE", default=1000),
        cycle_anchor_hour_utc=(
            _env_int(env, "TPOT2CTI_CYCLE_ANCHOR_HOUR_UTC", default=-1)
            if env.get("TPOT2CTI_CYCLE_ANCHOR_HOUR_UTC") else None
        ),
        transient_retry_seconds=_env_int(env, "TPOT2CTI_TRANSIENT_RETRY_SECONDS", default=60),
    )

    # --- Connector IDs ---
    connector_ids = ConnectorIDs(
        core=_env_str(env, "TPOT2CTI_CONNECTOR_ID", required=True),
        credentials=_env_str(env, "TPOT2CTI_CREDENTIALS_CONNECTOR_ID"),
        vault=_env_str(env, "TPOT2CTI_VAULT_CONNECTOR_ID"),
    )

    # --- Logging ---
    logging_cfg = LoggingConfig(
        level=(_env_str(env, "LOG_LEVEL", default="INFO") or "INFO").upper(),
        log_dir=_env_str(env, "LOG_DIR", default="/var/log/tpot2cti") or "/var/log/tpot2cti",
        retention_days=_env_int(env, "LOG_RETENTION_DAYS", default=30),
    )

    cfg = Config(
        tpot=tpot,
        es=es,
        opencti=opencti,
        operator=operator,
        cycle=cycle,
        connector_ids=connector_ids,
        logging=logging_cfg,
    )

    # Defer validation of cycle_anchor_hour_utc range (0-23)
    if cfg.cycle.cycle_anchor_hour_utc is not None:
        if not (0 <= cfg.cycle.cycle_anchor_hour_utc <= 23):
            raise ConfigError(
                f"TPOT2CTI_CYCLE_ANCHOR_HOUR_UTC must be 0-23 inclusive; "
                f"got {cfg.cycle.cycle_anchor_hour_utc}"
            )

    if cfg.operator.default_tlp not in ("CLEAR", "GREEN", "AMBER", "AMBER+STRICT", "RED"):
        raise ConfigError(
            f"TPOT2CTI_DEFAULT_TLP must be one of "
            f"CLEAR / GREEN / AMBER / AMBER+STRICT / RED; "
            f"got {cfg.operator.default_tlp!r}"
        )

    if not (0 <= cfg.operator.default_confidence <= 100):
        raise ConfigError(
            f"TPOT2CTI_DEFAULT_CONFIDENCE must be 0-100; "
            f"got {cfg.operator.default_confidence}"
        )

    logger.info(
        f"Config loaded: tpot={cfg.tpot.host}:{cfg.tpot.ssh_port} "
        f"es={cfg.es.scheme}://{cfg.es.host}:{cfg.es.port} "
        f"opencti={cfg.opencti.url} "
        f"cycle={cfg.cycle.interval_iso} "
        f"tlp={cfg.operator.default_tlp}"
    )
    return cfg


if __name__ == "__main__":
    # Smoke test
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    try:
        cfg = load_config()
        print("OK — config loaded:")
        print(f"  tpot: {cfg.tpot}")
        print(f"  es: {cfg.es}")
        print(f"  opencti.url: {cfg.opencti.url}")
        print(f"  operator: {cfg.operator}")
        print(f"  cycle: {cfg.cycle}")
        print(f"  connector_ids.core: {cfg.connector_ids.core}")
        print(f"  logging: {cfg.logging}")
    except ConfigError as e:
        print(f"FAIL: {e}", file=sys.stderr)
        sys.exit(1)
